name: NukkitQQSync Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  schwi-build:
    name: NukkitQQSync Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: joschi/setup-jdk@v2
        with:
          java-version: '8' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'

      - name: Build
        run: mvn package

      - name: Archieve Artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: NukkitQQSync.jar
          path: target/NukkitQQSync.jar
      - name: Upload binaries to release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            NukkitQQSync.jar
